services:

  mysql:
    image: mysql
    ports:
      - '${DATABASE_PORT:-3306}:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
#    volumes:
#        - 'xadis-pgsql:/var/lib/postgresql/data'
